-- Globalne vezbe za vrat iz "core" u "vrat". Spisak prati Neck kategoriju iz
-- izvorne biblioteke (name_en je originalni naziv), bez anatomskih kartica bez videa.
update public.exercises
set primary_muscle = 'vrat'
where is_global
  and primary_muscle = 'core'
  and lower(trim(name_en)) in (
    'lying neck flexion',
    'lying neck extension',
    'forward flexion neck stretch',
    'side neck stretch',
    'neck extension stretch',
    'neck circle stretch',
    'neck side stretch',
    'weighted side lying side neck raise',
    'rotating neck stretch',
    'seated neck extension',
    'chin tuck',
    'neck bridge prone',
    'diagonal flexion neck stretch',
    'lying neck extension stretch',
    'lying neck extensor stretch',
    'weighted seated neck extension',
    'weighted lying neck head twist',
    'lying side lifting head',
    'sitting neck flexion stretch',
    'front and back neck stretch',
    'weighted lying neck flexion',
    'neck extensor and rotational stretch',
    'weighted lying side neck raise',
    'backward forward turn to side neck stretch',
    'weighted lying neck side to side',
    'lying chin tucks',
    'weighted standing neck extension',
    'side push neck stretch',
    'neck protraction stretch',
    'lever neck extension',
    'lever neck left side flexion',
    'prone cervical extension',
    'chin tuck against the wall',
    'assisted chin tuck',
    'cable seated neck extension',
    'neck flexor and rotational stretch',
    'weighted lying neck extension',
    'extension and inclination neck stretch',
    'roll neck rotation lying on floor',
    'seated flexion and extension neck',
    'seated neck stretch',
    'lever neck right side flexion',
    'neck flexor stretch',
    'assisted rotating neck stretch',
    'prone cervical extension isometric hold',
    'cable seated neck flexion',
    'weighted lying side lifting head',
    'backward neck stretch',
    'posterior neck isometric',
    'superman floor touch',
    'roll neck decompress lying on floor',
    'roll neck decompress lying on floor (female)',
    'lying chin tuck raise',
    'standing side neck stretch',
    'seated chin tuck',
    'tiger tail neck',
    'neck stretch with hand assisted (female)',
    '5 sec fist against chin',
    'roll neck rotation lying on floor (female)',
    'lying scalene muscles activation (female)',
    'neck half circle',
    'head full rotation fpov',
    'neck-up down left right',
    'sitting neck stretch',
    'forward neck stretch',
    'roll ball side lying scalene muscles activation (female)',
    'roll ball side lying scalene muscles activation (side pov) (female)',
    -- u bazi je naziv sa greskom u kucanju ("semisplinalis")
    'roll ball lying semisplinalis capitis muscle activation (female)'
  );
